@startuml

left to right direction

actor Usuario
actor Estudiante
actor Profesor
actor Administrador
actor Departamento

rectangle "Gestión de Usuarios" {
    Usuario -- (Autenticar Usuario)
    Usuario -- (Actualizar Datos del Usuario)
}

rectangle "Gestión de Estudiantes" {
    Estudiante -- (Inscribirse en un Curso)
    Estudiante -- (Consultar Historial Académico)
    Administrador -- (Crear Estudiante)
    Administrador -- (Actualizar Estudiante)
    Administrador -- (Eliminar Estudiante)
    Administrador -- (Ver Estudiante)
}

rectangle "Gestión de Profesores" {
    Profesor -- (Asignar Notas)
    Profesor -- (Listar Cursos Asignados)
    Administrador -- (Crear Profesor)
    Administrador -- (Actualizar Profesor)
    Administrador -- (Eliminar Profesor)
    Administrador -- (Ver Profesor)
}

rectangle "Gestión de Cursos" {
    Administrador -- (Crear Curso)
    Administrador -- (Actualizar Curso)
    Administrador -- (Eliminar Curso)
    Estudiante -- (Listar Cursos)
    Profesor -- (Listar Cursos)
    Administrador -- (Asignar Profesor a Curso)
}

rectangle "Gestión de Inscripciones" {
    Estudiante -- (Registrar Inscripción)
    Estudiante -- (Realizar Pago de Inscripción)
}

rectangle "Gestión de Evaluaciones" {
    Profesor -- (Calcular Promedio de Evaluaciones)
}

rectangle "Gestión de Departamentos" {
    Administrador -- (Crear Departamento)
    Administrador -- (Actualizar Departamento)
    Administrador -- (Eliminar Departamento)
    Administrador -- (Ver Departamento)
    Departamento -- (Asignar Profesor a un Curso)
    Departamento -- (Listar Cursos de un Departamento)
}

@enduml
